---
- name: template_update_from_git
  hosts: localhost
  vars_files:
    - credentials.yml
  connection: local
  gather_facts: yes 
  vars: 
    # dnac_host: "{{dnac_host}}"
    # dnac_verify: false
    # dnac_username: "{{lookup('env','DNAC_USERNAME')}}"
    # dnac_password: "{{lookup('env','DNAC_PASSWORD')}}"
    # dnac_debug: yes
    DEBUG: "{{lookup('env','DEBUG')}}"
    # DNAC Template Summary field is length-limited to 1024 chars
    DNAC_TEMPLATE_SUMMARY_MAXCHAR: 1024

  tasks:

    - name: Set execution timestamp
      set_fact:
        start_timestamp: "{{ ansible_date_time }}"

    - name: --DEBUG-- Execution timestamp
      when: DEBUG is defined
      debug: 
        msg: "{{ start_timestamp.date + ' ' + start_timestamp.time}}"

    - name: Get Project name from matching Git repo
      set_fact:
        projectName: "{{ (git_repo | regex_search('.*\/([^\/]*).git', '\\1'))[0]}}"

    - name: --DEBUG-- Project Name
      when: DEBUG is defined
      debug: 
        msg: "{{ projectName }}"

    - name: Clone templates project from the GitHub repo
      ansible.builtin.git:
        accept_hostkey: yes
        repo: "{{git_repo}}"
        dest: "{{git_local_dest}}"
        update: yes
        force: yes
      register: git_clone_result

    - name: Get cloned template list
      find:
        paths: "{{git_local_dest}}"
        patterns: "*.{{template_extension}}"
        recurse: no
        file_type: file
      register: template_file_list

    - name: Get template commit messages
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%ad | %B [%an]\" -1 --date=short {{ item.path }}"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_log

    - name: Set template commit list
      set_fact:  
        template_commit_list: "{{ template_commit_list|default([]) + [ {'commit_msg': item.stdout,
                                                                        'name': item.cmd | regex_search('[^\\/]*$'),
                                                                        } ] }}"
      with_items: "{{ template_git_log.results }}"

    - name: --DEBUG-- template commit list
      when: DEBUG is defined
      debug:  
        msg: "{{ template_commit_list }}"

    - name: Get template diff log
      ansible.builtin.shell:
        cmd: "git log --pretty=format:\"%H\" -p -1 --date=short {{ item.path }}"
        chdir: "{{ item.path | dirname }}"
      with_items: "{{ template_file_list.files }}"
      register: template_git_diff

    - name: Set template diff list
      set_fact:  
        template_diff_list: "{{ template_diff_list|default([]) + [ {'diff_msg': item.stdout | regex_replace('([^\\n]+)', '{## \\1 ##}') + '\n' ,
                                                                    'name': item.cmd | regex_search('[^\\/]*$'),
                                                                    } ] 
                              }}"
      with_items: "{{ template_git_diff.results }}"

    - name: --DEBUG-- show template diff list
      when: DEBUG is defined
      debug:  
        msg: "{{ template_diff_list }}"

    - name: Set git template detail list
      set_fact:
        template_git_list: "{{ template_git_list|default([]) + [ {'name': (item.path | basename), 
                                                                  'id': '',
                                                                  'language': 'JINJA',
                                                                  'path': item.path,
                                                                  'payload': lookup('file',item.path),
                                                                  } ] }}"
      with_items: "{{ template_file_list.files }}"

    - name: --DEBUG-- show git template list
      when: DEBUG is defined
      debug:  
        msg: "{{ template_git_list }}"

    - name: Get matching template project name
      cisco.dnac.configuration_template_project_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        name: "{{projectName}}"
      register: template_project

    - name: Create new DNAC project if not found
      when: template_project.dnac_response | length == 0
      cisco.dnac.configuration_template_project:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        name: "{{projectName}}"

    - name: Get new template project name that we just created
      when: template_project.dnac_response | length == 0
      cisco.dnac.configuration_template_project_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        name: "{{projectName}}"
        register: template_project

    - name: --DEBUG-- create new project
      when: DEBUG is defined
      debug:
        msg: "{{ template_project }}"

    - name: Set matching DNAC Template Project
      set_fact:
        template_project: "{{ template_project.dnac_response[0] }}"

    - name: Setting existing templates list
      set_fact:
        template_dnac_list: "{{ template_project.templates }}"

    - name: Setting project id
      set_fact:
        template_project_id: "{{ template_project.id }}"

    - name: Merge template git + dnac >> id
      set_fact:
        template_id_list: "{{ template_git_list |
                              community.general.lists_mergeby(template_dnac_list, 'name')
                          }}"

    - name: Merge template id + commit >> id
      set_fact:
        template_id_list: "{{ template_id_list |
                              community.general.lists_mergeby(template_commit_list, 'name')
                          }}"

    - name: Merge template id + diff >> id
      set_fact:
        template_id_list: "{{ template_id_list |
                              community.general.lists_mergeby(template_diff_list, 'name')
                          }}"

    - name: --DEBUG-- show project id
      when: DEBUG is defined
      debug:
        msg: "{{ template_project_id }}"

    - name: --DEBUG-- show matching DNAC Project
      when: DEBUG is defined
      debug:
        msg: "{{ template_project }}"

    - name: --DEBUG-- show existing template list
      when: DEBUG is defined
      debug:
        msg: "{{ template_dnac_list }}"

    - name: --DEBUG-- show template id list 
      when: DEBUG is defined
      debug:
        msg: "{{ template_id_list }}"

    - name: Create new templates in DNAC
      when: item.id == ''
      cisco.dnac.configuration_template_create:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        author: "{{ dnac_username }}"
        composite: false
        description: "description"
        deviceTypes:
        - productFamily: "Routers"
        language: "{{ item.language }}"
        name: "{{ item.name }}"
        projectId: "{{ template_project_id }}"
        softwareType: "IOS-XE"
        templateContent: "{{ item.diff_msg + item.payload }}"
        version: "1.0"
      with_items: "{{ template_id_list }}"

    - name: Update existing templates in DNAC
      when: item.id != ''
      cisco.dnac.configuration_template:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        author: "{{ dnac_username }}"
        composite: false
        description: "description"
        deviceTypes:
        - productFamily: "Routers"
        name: "{{ item.name }}"
        id: "{{ item.id }}"
        language: "{{ item.language }}"
        projectId: "{{ template_project_id }}"
        softwareType: "IOS-XE"
        templateContent: "{{ item.diff_msg + item.payload }}"
      with_items: "{{ template_id_list }}"

    - name: Collecting renewed template list from DNAC
      cisco.dnac.configuration_template_project_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        name: "{{projectName}}"
      register: template_project_name

    - name: Set existing templates list
      set_fact:
        template_dnac_list: "{{ template_project_name.dnac_response[0].templates }}"

    - name: Re-create merged template id list
      set_fact:
        template_id_list: "{{ template_git_list |
                              community.general.lists_mergeby(template_dnac_list, 'name')
                          }}"

    - name: Re-create merged id + commit >> id
      set_fact:
        template_id_list: "{{ template_id_list |
                              community.general.lists_mergeby(template_commit_list, 'name')
                          }}"

    - name: --DEBUG-- show refreshed template list
      when: DEBUG is defined
      debug:
        msg: "{{ template_id_list }}"

    - name: Version DNAC templates
      cisco.dnac.configuration_template_version_create:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        comments: "{{ (item.commit_msg)[:DNAC_TEMPLATE_SUMMARY_MAXCHAR] }}"
        templateId: "{{ item.id }}"
      with_items: "{{ template_id_list }}"
  
